version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://server:3001
    depends_on:
      - server
    networks:
      - typewriter-network

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/typingapp
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
    networks:
      - typewriter-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: typingapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - typewriter-network

networks:
  typewriter-network:
    driver: bridge

volumes:
  postgres_data:
